// Blanc settings-schema generator (substrate S5).
//
//   node settings-schema/build.mjs           emit generated/{BlancSettings.swift,BlancSettings.kt}
//   node settings-schema/build.mjs --check    verify src/main/settings.js has not drifted from
//                                             schema.json, and the generated files are current.
//                                             Exit 1 on drift.
//
// Same shape as tokens/: one source (schema.json), desktop guarded (settings.js
// parsed and compared, not rewritten), mobile enums+defaults generated so the
// key/enum/default set is never hand-copied into two more languages.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SPEC = path.join(ROOT, 'settings-schema', 'schema.json');
const OUT = path.join(ROOT, 'settings-schema', 'generated');
const spec = JSON.parse(fs.readFileSync(SPEC, 'utf8'));

const SWIFT_RESERVED = new Set(['default', 'class', 'enum', 'case', 'func', 'import', 'public', 'private', 'static', 'protocol', 'in', 'is', 'let', 'var']);
const swiftCase = (id) => (SWIFT_RESERVED.has(id) ? `\`${id}\`` : id);
const upper = (id) => id.toUpperCase();

// ---- generators ----
function genSwift() {
  const engines = spec.searchEngines, icons = [...spec.appIcons, ...spec.supporterIcons.map((i) => ({ ...i, supporter: true }))];
  const supporterIds = new Set(spec.supporterIcons.map((i) => i.id));
  let out = '// GENERATED by settings-schema/build.mjs from schema.json — do not edit by hand.\n' +
            '// Blanc settings enums + defaults; mirror src/main/settings.js.\n\n' +
            'import Foundation\n\n';
  out += 'public enum BlancSearchEngine: String, CaseIterable {\n';
  for (const e of engines) out += `    case ${swiftCase(e.id)}\n`;
  out += '    public var label: String {\n        switch self {\n';
  for (const e of engines) out += `        case .${swiftCase(e.id)}: return ${JSON.stringify(e.label)}\n`;
  out += '        }\n    }\n}\n\n';
  out += 'public enum BlancThemePreference: String, CaseIterable {\n';
  for (const t of spec.themes) out += `    case ${swiftCase(t)}\n`;
  out += '}\n\n';
  out += 'public enum BlancAppIcon: String, CaseIterable {\n';
  for (const i of icons) out += `    case ${swiftCase(i.id)}\n`;
  out += '    public var label: String {\n        switch self {\n';
  for (const i of icons) out += `        case .${swiftCase(i.id)}: return ${JSON.stringify(i.label)}\n`;
  out += '        }\n    }\n';
  out += '    public var isSupporterOnly: Bool {\n        switch self {\n';
  out += `        case ${[...supporterIds].map((id) => `.${swiftCase(id)}`).join(', ')}: return true\n`;
  out += '        default: return false\n        }\n    }\n}\n\n';
  out += 'public struct BlancSettingsDefaults {\n';
  out += `    public static let searchEngine: BlancSearchEngine = .${swiftCase(spec.defaults.searchEngine)}\n`;
  out += `    public static let adblockEnabled: Bool = ${spec.defaults.adblockEnabled}\n`;
  out += `    public static let homePage: String = ${JSON.stringify(spec.defaults.homePage)}\n`;
  out += `    public static let theme: BlancThemePreference = .${swiftCase(spec.defaults.theme)}\n`;
  out += `    public static let appIcon: BlancAppIcon = .${swiftCase(spec.defaults.appIcon)}\n`;
  out += `    public static let usagePing: Bool = ${spec.defaults.usagePing}\n`;
  out += '    // adblockExceptions defaults to []; supporter defaults to nil (structural).\n}\n';
  return out;
}

function genKotlin() {
  const icons = [...spec.appIcons.map((i) => ({ ...i, sup: false })), ...spec.supporterIcons.map((i) => ({ ...i, sup: true }))];
  let out = '// GENERATED by settings-schema/build.mjs from schema.json — do not edit by hand.\n' +
            '// Blanc settings enums + defaults; mirror src/main/settings.js.\n\n' +
            'package me.bnfy.blanc.settings\n\n';
  out += 'enum class BlancSearchEngine(val id: String, val label: String) {\n';
  out += spec.searchEngines.map((e) => `    ${upper(e.id)}("${e.id}", ${JSON.stringify(e.label)})`).join(',\n') + ';\n}\n\n';
  out += 'enum class BlancThemePreference(val id: String) {\n';
  out += spec.themes.map((t) => `    ${upper(t)}("${t}")`).join(',\n') + ';\n}\n\n';
  out += 'enum class BlancAppIcon(val id: String, val label: String, val isSupporterOnly: Boolean) {\n';
  out += icons.map((i) => `    ${upper(i.id)}("${i.id}", ${JSON.stringify(i.label)}, ${i.sup})`).join(',\n') + ';\n}\n\n';
  out += 'object BlancSettingsDefaults {\n';
  out += `    val searchEngine = BlancSearchEngine.${upper(spec.defaults.searchEngine)}\n`;
  out += `    const val adblockEnabled = ${spec.defaults.adblockEnabled}\n`;
  out += `    const val homePage = ${JSON.stringify(spec.defaults.homePage)}\n`;
  out += `    val theme = BlancThemePreference.${upper(spec.defaults.theme)}\n`;
  out += `    val appIcon = BlancAppIcon.${upper(spec.defaults.appIcon)}\n`;
  out += `    const val usagePing = ${spec.defaults.usagePing}\n`;
  out += '    // adblockExceptions defaults to emptyList(); supporter defaults to null (structural).\n}\n';
  return out;
}

const ARTIFACTS = { 'BlancSettings.swift': genSwift(), 'BlancSettings.kt': genKotlin() };

// ---- parse the stable structures out of settings.js ----
function parseSettingsJs() {
  // Strip /* */ block comments, and anchor every pattern to line start (^\s*, /m)
  // so a `//` line comment (or a commented-out key) is never read as a live value
  // — that would let real drift pass. Anchoring is used instead of stripping `//`
  // because a value string can legitimately contain `//` (e.g. a homePage URL).
  const js = fs.readFileSync(path.join(ROOT, spec.source), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
  // Label maps can be single-line (SUPPORTER_ICON_LABELS) so line-anchoring
  // won't work; strip // line comments instead (label values never contain //).
  const pairs = (block) => [...String(block ?? '').replace(/\/\/.*$/gm, '').matchAll(/(\w+):\s*'([^']+)'/g)].map((m) => ({ id: m[1], label: m[2] }));
  const engines = [...js.matchAll(/^\s*(\w+):\s*\{\s*label:\s*'([^']+)'/gm)].map((m) => ({ id: m[1], label: m[2] }));
  // THEMES may be multiline; strip // comments from its block (theme ids never
  // contain //) so a commented-out entry like `// 'dark'` isn't read as live.
  const themesBlock = (js.match(/const THEMES = \[([^\]]*)\]/)?.[1] ?? '').replace(/\/\/.*$/gm, '');
  const themes = [...themesBlock.matchAll(/'([^']+)'/g)].map((m) => m[1]);
  const appIcons = pairs(js.match(/const APP_ICON_LABELS = \{([\s\S]*?)\}/)?.[1]);
  const supporterIcons = pairs(js.match(/const SUPPORTER_ICON_LABELS = \{([\s\S]*?)\}/)?.[1]);
  const D = js.match(/const DEFAULTS = \{([\s\S]*?)\n\};/)?.[1] ?? '';
  const s = (re) => D.match(re)?.[1];
  const defaults = {
    searchEngine: s(/^\s*searchEngine:\s*'([^']*)'/m),
    adblockEnabled: s(/^\s*adblockEnabled:\s*(true|false)/m),
    homePage: s(/^\s*homePage:\s*'([^']*)'/m),
    theme: s(/^\s*theme:\s*'([^']*)'/m),
    appIcon: s(/^\s*appIcon:\s*'([^']*)'/m),
    usagePing: s(/^\s*usagePing:\s*(true|false)/m),
    adblockExceptionsEmpty: /^\s*adblockExceptions:\s*\[\]/m.test(D),
    supporterNull: /^\s*supporter:\s*null/m.test(D),
  };
  return { engines, themes, appIcons, supporterIcons, defaults };
}

function check() {
  const problems = [];
  const js = parseSettingsJs();
  const fmt = (arr) => arr.map((x) => (x.label != null ? `${x.id}:${x.label}` : x)).join(', ');
  const cmp = (name, a, b) => { if (fmt(a) !== fmt(b)) problems.push(`${name}\n  settings.js: ${fmt(a)}\n  schema.json: ${fmt(b)}`); };

  cmp('searchEngines', js.engines, spec.searchEngines);
  cmp('themes', js.themes, spec.themes);
  cmp('appIcons', js.appIcons, spec.appIcons);
  cmp('supporterIcons', js.supporterIcons, spec.supporterIcons);

  const d = spec.defaults, jd = js.defaults;
  const eq = (k, got, want) => { if (got !== want) problems.push(`defaults.${k}: settings.js=${JSON.stringify(got)} schema.json=${JSON.stringify(want)}`); };
  eq('searchEngine', jd.searchEngine, d.searchEngine);
  eq('adblockEnabled', jd.adblockEnabled, String(d.adblockEnabled));
  eq('homePage', jd.homePage, d.homePage);
  eq('theme', jd.theme, d.theme);
  eq('appIcon', jd.appIcon, d.appIcon);
  eq('usagePing', jd.usagePing, String(d.usagePing));
  if (!jd.adblockExceptionsEmpty) problems.push('defaults.adblockExceptions: settings.js is not []');
  if (!jd.supporterNull) problems.push('defaults.supporter: settings.js is not null');

  let failed = problems.length > 0;
  if (failed) console.error('DRIFT (src/main/settings.js vs schema.json):\n' + problems.map((p) => '  ' + p).join('\n'));

  for (const [name, content] of Object.entries(ARTIFACTS)) {
    const p = path.join(OUT, name);
    const onDisk = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
    if (onDisk !== content) { failed = true; console.error(`STALE: settings-schema/generated/${name} — run \`npm run settings:build\``); }
  }

  if (failed) { console.error('\nsettings:check failed.'); process.exit(1); }
  console.log('settings:check OK — settings.js matches the schema, generated files current.');
}

function build() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, content] of Object.entries(ARTIFACTS)) {
    fs.writeFileSync(path.join(OUT, name), content);
    console.log(`wrote settings-schema/generated/${name}`);
  }
}

process.argv.includes('--check') ? check() : build();
