// Blanc design-token generator (substrate S2).
//
//   node tokens/build.mjs           emit tokens/generated/{Tokens.swift,Tokens.kt,tokens.css}
//   node tokens/build.mjs --check   verify: (1) the live desktop CSS (styles.css /
//                                   pages.css) has not drifted from tokens.json, and
//                                   (2) the generated files are up to date. Exit 1 on drift.
//
// One source (tokens/tokens.json), many consumers. Desktop CSS is *guarded* here
// rather than rewritten (the chrome CSS can't be visually re-verified from a
// headless build); the mobile Swift/Kotlin files ARE generated, so the palette
// never has to be hand-copied into two more languages.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'tokens', 'tokens.json');
const OUT = path.join(ROOT, 'tokens', 'generated');

const spec = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const isThemed = (t) => 'light' in t.values;
const forConsumer = (c) => spec.tokens.filter((t) => t.consumers.includes(c));
const camel = (n) => n.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// ---- expected token maps per scope, from the source ----
function expected(consumer) {
  const light = new Map(), dark = new Map(), priv = new Map();
  for (const t of forConsumer(consumer)) {
    light.set(t.name, isThemed(t) ? t.values.light : t.values.common);
    if (isThemed(t)) { dark.set(t.name, t.values.dark); priv.set(t.name, t.values.private); }
  }
  return { light, dark, private: priv };
}

// ---- parse the :root / dark / private blocks out of a live CSS file ----
function parseCss(css) {
  const bare = [...css.matchAll(/:root\s*\{([^}]*)\}/g)].map((m) => m[1]); // [0]=light, [1]=dark inner
  const priv = css.match(/:root\[data-theme="private"\]\s*\{([^}]*)\}/);
  const decls = (block) => {
    const map = new Map();
    for (const m of (block ?? '').matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) map.set(m[1], m[2].trim());
    return map;
  };
  return { light: decls(bare[0]), dark: decls(bare[1]), private: decls(priv?.[1]) };
}

function diffMaps(exp, act) {
  const problems = [];
  for (const [k, v] of exp) {
    if (!act.has(k)) problems.push(`  missing --${k} (expected "${v}")`);
    else if (act.get(k) !== v) problems.push(`  --${k}: css has "${act.get(k)}", source says "${v}"`);
  }
  for (const k of act.keys()) if (!exp.has(k)) problems.push(`  unexpected --${k}="${act.get(k)}" not in source`);
  return problems;
}

// ---- generators ----
function genCss() {
  let out = '/* GENERATED from tokens/tokens.json — reference for a future flip to\n' +
            '   codegen. The live styles.css / pages.css are hand-written and guarded\n' +
            '   against drift by `npm run tokens:check`, not overwritten by this file. */\n';
  for (const consumer of Object.keys(spec.consumers)) {
    const toks = forConsumer(consumer);
    const line = (t, scope) => `  --${t.name}: ${scope === 'common' ? t.values.common : t.values[scope]};`;
    out += `\n/* ${consumer} — ${spec.consumers[consumer]} */\n:root {\n`;
    out += toks.map((t) => line(t, isThemed(t) ? 'light' : 'common')).join('\n') + '\n}\n';
    const themed = toks.filter(isThemed);
    out += `@media (prefers-color-scheme: dark) {\n  :root {\n`;
    out += themed.map((t) => '  ' + line(t, 'dark')).join('\n') + '\n  }\n}\n';
    out += `:root[data-theme="private"] {\n`;
    out += themed.map((t) => line(t, 'private')).join('\n') + '\n}\n';
  }
  return out;
}

function genSwift() {
  const themed = spec.tokens.filter(isThemed);
  const common = spec.tokens.filter((t) => !isThemed(t));
  const scopeCase = { light: 'light', dark: 'dark', private: 'privateBrowsing' };
  let out = '// GENERATED by tokens/build.mjs from tokens/tokens.json — do not edit by hand.\n' +
            '// Blanc design tokens; values mirror the desktop CSS custom properties.\n' +
            '// Colors are hex/rgba strings; wrap them in Color/UIColor at the call site.\n\n' +
            'import Foundation\n\n' +
            'public enum BlancTheme: String, CaseIterable {\n    case light\n    case dark\n    case privateBrowsing\n}\n\n' +
            'public enum BlancTokens {\n';
  for (const t of themed) {
    out += `    public static func ${camel(t.name)}(_ theme: BlancTheme) -> String {\n        switch theme {\n`;
    for (const s of spec.themes) out += `        case .${scopeCase[s]}: return ${JSON.stringify(t.values[s])}\n`;
    out += '        }\n    }\n';
  }
  for (const t of common) out += `    public static let ${camel(t.name)} = ${JSON.stringify(t.values.common)}\n`;
  out += '}\n';
  return out;
}

function genKotlin() {
  const themed = spec.tokens.filter(isThemed);
  const common = spec.tokens.filter((t) => !isThemed(t));
  const scopeEnum = { light: 'LIGHT', dark: 'DARK', private: 'PRIVATE' };
  let out = '// GENERATED by tokens/build.mjs from tokens/tokens.json — do not edit by hand.\n' +
            '// Blanc design tokens; values mirror the desktop CSS custom properties.\n' +
            '// Colors are hex/rgba strings; wrap them in Color at the call site.\n\n' +
            'package me.bnfy.blanc.tokens\n\n' +
            'enum class BlancTheme { LIGHT, DARK, PRIVATE }\n\n' +
            'object BlancTokens {\n';
  for (const t of themed) {
    out += `    fun ${camel(t.name)}(theme: BlancTheme): String = when (theme) {\n`;
    for (const s of spec.themes) out += `        BlancTheme.${scopeEnum[s]} -> ${JSON.stringify(t.values[s])}\n`;
    out += '    }\n';
  }
  for (const t of common) out += `    const val ${camel(t.name)}: String = ${JSON.stringify(t.values.common)}\n`;
  out += '}\n';
  return out;
}

const ARTIFACTS = { 'Tokens.swift': genSwift(), 'Tokens.kt': genKotlin(), 'tokens.css': genCss() };

// ---- modes ----
function build() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, content] of Object.entries(ARTIFACTS)) {
    fs.writeFileSync(path.join(OUT, name), content);
    console.log(`wrote tokens/generated/${name}`);
  }
}

function check() {
  let failed = false;

  // (1) live CSS drift
  for (const [consumer, rel] of Object.entries(spec.consumers)) {
    const css = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    const act = parseCss(css);
    const exp = expected(consumer);
    for (const scope of ['light', 'dark', 'private']) {
      const problems = diffMaps(exp[scope], act[scope]);
      if (problems.length) {
        failed = true;
        console.error(`DRIFT: ${rel} [${scope}]\n${problems.join('\n')}`);
      }
    }
  }

  // (2) generated files freshness
  for (const [name, content] of Object.entries(ARTIFACTS)) {
    const p = path.join(OUT, name);
    const onDisk = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
    if (onDisk !== content) {
      failed = true;
      console.error(`STALE: tokens/generated/${name} — run \`npm run tokens:build\``);
    }
  }

  if (failed) { console.error('\ntokens:check failed.'); process.exit(1); }
  console.log('tokens:check OK — desktop CSS matches the source, generated files current.');
}

process.argv.includes('--check') ? check() : build();
